//! PyBaMM **DFN** golden-reference tolerance tests (Phase 7, slice D).
//!
//! These replay a committed PyBaMM DFN trajectory through `sim-core`'s own `Dfn` and
//! assert the terminal voltage tracks it within a documented, per-scenario tolerance. The
//! reference CSVs live under `tests/golden/nmc_21700_lgm50/` and are (re)generated by
//! `tools/reference/generate.py` (needs PyBaMM; never on the Rust/CI path). Columns:
//! `time_s, current_a` (discharge-positive), `voltage_v`, `soc`.
//!
//! Together these carry **Phase 7's exit criterion 2**: a pack configured with
//! `CellModel::Dfn` runs and matches a committed DFN golden, and at least one scenario
//! reaches electrolyte depletion — the regime a single-particle model cannot represent at
//! all, and therefore the only one that proves the phase did something. That last clause is
//! not rhetoric here: [`the_spm_cannot_follow_the_reference_into_depletion`] measures it.
//!
//! # How this differs from `spm_golden.rs`, and from `pybamm_golden.rs`
//! `pybamm_golden.rs` compares an **ECM against a DFN** — two different models — so its
//! tolerances are dominated by an irreducible modelling gap and have to be confined to SOC
//! windows. `spm_golden.rs` compares batsim's SPM against PyBaMM's SPM: same model form,
//! same parameter set, so the disagreement is implementation and discretisation only.
//!
//! This file is the second kind. Both sides are Doyle–Fuller–Newman on Chen2020, so the
//! residual is three things and nothing else:
//!
//! * **The OCP tables.** batsim interpolates two committed tables; PyBaMM evaluates
//!   Chen2020's fitted functions. Their documented interpolation error is 1.90 mV
//!   (graphite) and 1.88 mV (NMC), a floor no grid can get under.
//! * **The grids.** batsim runs the recommended x-grid and shell count named below; the
//!   reference runs 200 radial points on PyBaMM's own converged x-grid.
//! * **The timestep.** batsim takes one backward-Euler step per CSV row; the reference is
//!   adaptive at `rtol = atol = 1e-10`. As in the SPM goldens this shows up as the largest
//!   single-row disagreement sitting at the **first** step, where the gradients establish
//!   fastest.
//!
//! # The grid these run on is the *recommended* one, which is not the most accurate one
//! [`dfn::DEFAULT_NODES_NEGATIVE`] and its siblings (10/5/10) came out of the Phase 7
//! spike's **cost** table and were adopted without an accuracy measurement; slice D made
//! that measurement and it is recorded in
//! [`refining_the_x_grid_converges_toward_the_reference`] rather than acted on. These tests
//! deliberately assert at the recommendation, because that is what a caller who reads the
//! docs and does nothing else will get. A reader who wants the tighter number is told where
//! it is and what it costs.

use sim_core::dfn::{DEFAULT_NODES_NEGATIVE, DEFAULT_NODES_POSITIVE, DEFAULT_NODES_SEPARATOR};
use sim_core::spm::DEFAULT_SHELLS;
use sim_core::{
    CellModelConfig, ChemistryParams, Demand, Env, EventFlags, Pack, PackConfig, Scatter,
    ThermalConfig,
};

/// One reference sample.
struct Row {
    /// Simulation time \[s\].
    t: f64,
    /// Applied current over the step ending at `t` \[A\], discharge-positive.
    i: f64,
    /// Reference terminal voltage at `t` \[V\].
    v: f64,
    /// Throughput state of charge at `t`, in \[0, 1\].
    soc: f64,
}

/// Parse a golden CSV (skips `#` header lines and the column header).
fn parse_csv(text: &str) -> Vec<Row> {
    text.lines()
        .map(str::trim)
        .filter(|l| !l.is_empty() && !l.starts_with('#') && !l.starts_with("time_s"))
        .map(|l| {
            let mut f = l.split(',');
            let mut next = || f.next().unwrap().parse::<f64>().unwrap();
            Row {
                t: next(),
                i: next(),
                v: next(),
                soc: next(),
            }
        })
        .collect()
}

const CC_1C: &str = include_str!("../../../tests/golden/nmc_21700_lgm50/dfn_cc_1c_25c.csv");
const CC_3C: &str = include_str!("../../../tests/golden/nmc_21700_lgm50/dfn_cc_3c_25c.csv");

/// Nominal capacity of the shipped cell \[A·h\]. Not `5.0` — the file says 5.153198, and
/// `CLAUDE.md`'s parameter block is a shape rather than a source.
const CAPACITY_AH: f64 = 5.153198;

/// Discharge cut-off \[V\] for the shipped cell.
const V_CUT: f64 = 2.5;

/// The x-grid these tests assert at: the shipped recommendation.
const RECOMMENDED_NODES: (usize, usize, usize) = (
    DEFAULT_NODES_NEGATIVE,
    DEFAULT_NODES_SEPARATOR,
    DEFAULT_NODES_POSITIVE,
);

fn lgm50() -> ChemistryParams {
    let text = include_str!("../../../chemistries/nmc_21700_lgm50.toml");
    sim_data::parse_chemistry(text).expect("LG M50 chemistry loads")
}

fn env_25c() -> Env {
    Env {
        t_ambient: 298.15,
        t_coolant: None,
    }
}

fn dfn(nodes: (usize, usize, usize), shells: usize) -> CellModelConfig {
    CellModelConfig::Dfn {
        shells,
        nodes_negative: nodes.0,
        nodes_separator: nodes.1,
        nodes_positive: nodes.2,
    }
}

fn cfg(model: CellModelConfig, initial_soc: f64) -> PackConfig {
    PackConfig {
        series: 1,
        parallel: 1,
        initial_soc,
        initial_temp_k: 298.15,
        seed: 0,
        scatter: Scatter::default(),
        thermal: ThermalConfig::Isothermal,
        bms: None,
        aging: None,
        cell_model: model,
    }
}

/// Replay a reference current profile through a 1S1P pack. Returns batsim's terminal
/// voltage and SOC readout at every row (row 0 mirrors the reference's initial values, so
/// the comparison starts at row 1).
///
/// Isothermal and BMS-less for the same reason `spm_golden.rs` is: the reference is
/// isothermal, and a protection layer clamping a demand would make this a test of the clamp.
fn replay(rows: &[Row], model: CellModelConfig) -> (Vec<f64>, Vec<f64>) {
    let mut pack =
        Pack::new(&cfg(model, rows[0].soc), lgm50()).expect("a pack on this chemistry builds");
    let env = env_25c();

    let mut v = Vec::with_capacity(rows.len());
    let mut soc = Vec::with_capacity(rows.len());
    v.push(rows[0].v);
    soc.push(rows[0].soc);
    for w in rows.windows(2) {
        let tele = pack.step(w[1].t - w[0].t, Demand::Current(w[1].i), &env);
        v.push(tele.v_terminal);
        soc.push(tele.soc_true);
    }
    (v, soc)
}

/// Worst `|batsim − reference|` terminal voltage over rows at or before `t_max`, and the
/// SOC it occurred at.
fn worst_v_error(rows: &[Row], batsim: &[f64], t_max: f64) -> (f64, f64) {
    let mut worst = 0.0_f64;
    let mut at = f64::NAN;
    for (r, &vb) in rows.iter().zip(batsim).skip(1) {
        if r.t > t_max {
            break;
        }
        let e = (vb - r.v).abs();
        if e > worst {
            worst = e;
            at = r.soc;
        }
    }
    (worst, at)
}

/// Every batsim voltage must be finite and inside this cell's own window plus a margin.
fn assert_physical(name: &str, batsim: &[f64], upper: usize) {
    for (k, &v) in batsim.iter().enumerate().take(upper) {
        assert!(
            v.is_finite() && (2.0..=4.5).contains(&v),
            "{name}: batsim V={v} at row {k} left the physical band [2.0, 4.5]"
        );
    }
}

/// Discharge a pack of our own at constant current until it reaches the cut-off, returning
/// `(seconds, amp-hours)`. Distinct from [`replay`]: a replay is driven by the reference's
/// clock and says nothing about *when batsim would have stopped*, which for the depletion
/// scenario is the whole physics claim.
fn run_to_cutoff(model: CellModelConfig, i: f64, dt: f64) -> (f64, f64) {
    let mut p = Pack::new(&cfg(model, 1.0), lgm50()).expect("pack builds");
    let env = env_25c();
    let mut t = 0.0;
    for _ in 0..10_000 {
        let tele = p.step(dt, Demand::Current(i), &env);
        t += dt;
        if !tele.v_terminal.is_finite() || tele.v_terminal <= V_CUT {
            break;
        }
    }
    (t, i * t / 3600.0)
}

// ---------------------------------------------------------------------------
// 1C: the whole trajectory, no window
// ---------------------------------------------------------------------------

#[test]
fn dfn_cc_1c_tracks_pybamm_dfn() {
    // 1C from full to the 2.5 V cut-off, sampled every 5 s, compared over the **whole**
    // trajectory including the cut-off knee. No SOC window — the same claim
    // `spm_golden.rs` makes and a stronger one than any windowed bound, and available here
    // for the same reason: both sides are the same model on the same parameters.
    let rows = parse_csv(CC_1C);
    assert!(
        rows.len() > 100,
        "cc_1c: too few rows — CSV format changed?"
    );
    let (v, soc) = replay(&rows, dfn(RECOMMENDED_NODES, DEFAULT_SHELLS));
    let (worst, at) = worst_v_error(&rows, &v, f64::INFINITY);

    // Measured **5.83 mV**, at the *first* step (soc ≈ 0.9986), where the radial and
    // electrolyte gradients both establish inside one 5 s backward-Euler step. Every later
    // row sits under 2.2 mV — within a small multiple of the OCP tables' own 1.88/1.90 mV
    // interpolation floor, which is as close as this comparison can get.
    //
    // 12 mV is that first step with room. Which knob it is answerable to was measured
    // rather than assumed, and the two disagree: the **shell count** moves it a great deal
    // (23.4 mV at `N_r = 10` against 5.83 here), while the **x-grid** leaves it alone
    // (6.38 mV at 30/15/30 — very slightly worse). A first-step error is where the radial
    // gradient establishes, so that is the expected split; it is recorded because the
    // opposite is true at 3C, and a bound whose sensitivity is guessed is a bound nobody
    // can move safely later.
    assert!(
        worst < 0.012,
        "cc_1c worst error {:.2} mV (at soc {at:.4}) exceeds 12 mV",
        worst * 1e3
    );
    assert_physical("cc_1c", &v, v.len());

    // The SOC readout is a different claim from the voltage: for a DFN it is read off the
    // lithium inventory, not counted, so agreeing with the reference's coulomb count is a
    // check on the finite-volume scheme's conservation. Measured 4.4e-7 — the reference's
    // own six-decimal capacity rounding, exactly as in the SPM goldens.
    let worst_soc = rows
        .iter()
        .zip(&soc)
        .skip(1)
        .map(|(r, &s)| (s - r.soc).abs())
        .fold(0.0_f64, f64::max);
    assert!(
        worst_soc < 5e-6,
        "the DFN soc readout drifts from the reference coulomb count by {worst_soc:.2e}"
    );
}

// ---------------------------------------------------------------------------
// 3C: depletion, which is the scenario criterion 2 is really about
// ---------------------------------------------------------------------------

/// The reference's own duration \[s\]; every 3C window below is stated as a fraction of it.
fn ref_3c_duration(rows: &[Row]) -> f64 {
    rows[rows.len() - 1].t
}

#[test]
fn dfn_cc_3c_tracks_the_reference_into_depletion() {
    // 3C from full, sampled every 2 s. The reference reaches **complete electrolyte
    // depletion** (its minimum `c_e` touches zero and 89.8 % of the run has some node below
    // 100 mol/m³) and cuts off after 488.7 s having delivered 2.098 of 5.153 A·h. That is
    // the regime this phase exists for.
    let rows = parse_csv(CC_3C);
    assert!(
        rows.len() > 100,
        "cc_3c: too few rows — CSV format changed?"
    );
    let (v, _) = replay(&rows, dfn(RECOMMENDED_NODES, DEFAULT_SHELLS));

    // # Why this one is windowed when the 1C test is not
    //
    // A replay is driven by the *reference's* clock: it applies the reference's current at
    // the reference's timestamps regardless of what batsim's own cell is doing. At the
    // recommended grid batsim's 3C cell reaches its cut-off at 464 s, ~5 % before the
    // reference's 488.7 s, so the last handful of rows drive a cell that has already
    // collapsed. Comparing voltages there compares a dead cell to a live one and measures
    // nothing but the 5 % timing difference, magnified by the steepest part of the curve.
    //
    // So the voltage claim stops at 90 % of the reference's duration, and the timing
    // difference is asserted separately and directly by
    // [`dfn_cc_3c_lands_on_the_references_cut_off`] — which is the honest place for it.
    let window = 0.90 * ref_3c_duration(&rows);
    let (worst, at) = worst_v_error(&rows, &v, window);

    // Measured **62.1 mV** at the recommended 10/5/10 grid. An order of magnitude looser
    // than the 1C bound, and the reason is the grid rather than the model: at 20/10/20 the
    // same window measures 21.8 mV and everything after the first step is under 10.5 mV.
    // See `refining_the_x_grid_converges_toward_the_reference`.
    //
    // 100 mV is that measurement with room. It is deliberately not tightened to 65 mV: a
    // bound sitting on its measurement turns every ordinary grid or solver change into a
    // failure that reads as a physics regression, which is the trap the 3C cliff assertion
    // in `dfn_cell.rs` fell into and that slice D had to undo.
    assert!(
        worst < 0.100,
        "cc_3c worst error {:.1} mV (at soc {at:.4}) over the first 90 % of the \
         reference's run exceeds 100 mV",
        worst * 1e3
    );

    let n = rows.iter().take_while(|r| r.t <= window).count();
    assert_physical("cc_3c", &v, n);
}

#[test]
fn dfn_cc_3c_lands_on_the_references_cut_off() {
    // The depletion claim that a replay cannot make: run batsim's own cell at 3C and ask
    // when *it* stops and how much it delivers. Reference: 488.7 s, 2.098 A·h.
    //
    // # This is the assertion slice D was written around
    // Before slice D the shipped cell answered **726 s / 3.118 A·h** here — 49 % long, and
    // getting worse under grid refinement (768 s at 40/20/40). The cause was the kinetics
    // surface clamp disabling the choke that ends a hard discharge, so the positive
    // electrode accepted lithium past `c_max`; see [`sim_core::dfn::SURFACE_EDGE_FRACTION`]
    // and `dfn_cell.rs`'s `the_solid_phase_never_holds_more_than_it_can`.
    let (t, ah) = run_to_cutoff(
        dfn(RECOMMENDED_NODES, DEFAULT_SHELLS),
        3.0 * CAPACITY_AH,
        2.0,
    );

    // Measured 464 s / 1.993 A·h: 5.1 % short of the reference on both, in the direction a
    // coarse x-grid predicts (an under-resolved reaction front saturates its most-loaded
    // node slightly early). Refining moves it onto the reference and then 1.5 % past —
    // 490 s at 20/10/20, 496 s at 40/20/40 — i.e. it *converges*, which is the property the
    // pre-slice-D model did not have.
    //
    // ±12 % brackets the recommended grid and every refinement of it, and is far tighter
    // than the 49 % the defect was worth.
    assert!(
        (430.0..=548.0).contains(&t),
        "3C cut-off at {t} s is outside ±12 % of the reference's 488.7 s"
    );
    assert!(
        (1.85..=2.35).contains(&ah),
        "3C delivered {ah} A·h against the reference's 2.098"
    );
}

#[test]
fn the_spm_cannot_follow_the_reference_into_depletion() {
    // Criterion 2's rationale, as a measurement rather than a claim: replay the *same* 3C
    // depletion reference through a single-particle model. If the SPM tracked it as well as
    // the DFN, the phase would have bought nothing and every tolerance above would be
    // measuring something other than the electrolyte.
    let rows = parse_csv(CC_3C);
    let window = 0.90 * ref_3c_duration(&rows);
    let (v_dfn, _) = replay(&rows, dfn(RECOMMENDED_NODES, DEFAULT_SHELLS));
    let (v_spm, _) = replay(
        &rows,
        CellModelConfig::Spm {
            shells: DEFAULT_SHELLS,
        },
    );
    let (dfn_err, _) = worst_v_error(&rows, &v_dfn, window);
    let (spm_err, _) = worst_v_error(&rows, &v_spm, window);

    // Measured 62.1 mV (DFN) against 521.0 mV (SPM) — 8.4×. At the end of the replay the
    // SPM reads 3.42 V where the reference is at 2.59: it does not know the cell is dying,
    // because the quantity that is killing it is the one an SPM holds constant.
    assert!(
        spm_err > 4.0 * dfn_err,
        "the SPM tracked the depletion reference to {:.1} mV against the DFN's {:.1} mV — \
         less than 4x worse. Either the DFN has stopped solving for the electrolyte or this \
         scenario no longer reaches a regime that distinguishes them.",
        spm_err * 1e3,
        dfn_err * 1e3
    );
    assert!(
        spm_err > 0.2,
        "the SPM is only {:.1} mV from a DFN reference that depletes its electrolyte; \
         this scenario is not the discriminating one it is documented to be",
        spm_err * 1e3
    );
}

// ---------------------------------------------------------------------------
// The grid recommendation, measured rather than assumed
// ---------------------------------------------------------------------------

#[test]
fn refining_the_x_grid_converges_toward_the_reference() {
    // The finding slice D recorded and deliberately did **not** act on: the shipped
    // 10/5/10 recommendation came from the Phase 7 spike's *cost* table, and its accuracy
    // was never measured. It is here so the recommendation's price is a committed number
    // rather than a sentence someone has to trust.
    //
    // Measured at `DEFAULT_SHELLS`, 3C, over the first 90 % of the reference's run:
    //
    //   grid        cut-off      |err|       worst dV in window
    //   10/5/10     464 s        24.7 s      62.1 mV
    //   20/10/20    490 s         1.3 s      21.8 mV
    //   30/15/30    494 s         5.3 s
    //   40/20/40    496 s         7.3 s
    //
    // At 1C the picture inverts: the x-grid is worth nothing (5.83 mV at 10/5/10 against
    // 6.22 mV at 20/10/20 — refining is very slightly *worse*) and the shell count is the
    // knob that matters (23.4 mV at 10 shells against 5.8 at 20). Two knobs, each decisive
    // on a different scenario, which is why neither default moves on one measurement.
    //
    // # What this asserts, and why it is a direction rather than a value
    // That refining *helps at 3C*. Before slice D it did the opposite — 726 → 768 s, away
    // from the reference — and that divergence-under-refinement is what identified the
    // surface-clamp defect in the first place, since an error that grows as the grid
    // improves is not a discretisation error. Pinning the direction pins the diagnostic.
    let rows = parse_csv(CC_3C);
    let window = 0.90 * ref_3c_duration(&rows);
    let t_ref = 488.7;

    let coarse = dfn(RECOMMENDED_NODES, DEFAULT_SHELLS);
    let fine = dfn((20, 10, 20), DEFAULT_SHELLS);

    let (t_coarse, _) = run_to_cutoff(coarse, 3.0 * CAPACITY_AH, 2.0);
    let (t_fine, _) = run_to_cutoff(fine, 3.0 * CAPACITY_AH, 2.0);
    assert!(
        (t_fine - t_ref).abs() < (t_coarse - t_ref).abs(),
        "refining 10/5/10 -> 20/10/20 moved the 3C cut-off from {t_coarse} s to {t_fine} s, \
         which is no closer to the reference's {t_ref} s. Refinement diverging from the \
         reference is the signature of a defect rather than of discretisation — it is how \
         slice D found the surface-clamp one."
    );

    let (e_coarse, _) = worst_v_error(&rows, &replay(&rows, coarse).0, window);
    let (e_fine, _) = worst_v_error(&rows, &replay(&rows, fine).0, window);
    assert!(
        e_fine < e_coarse,
        "refining 10/5/10 -> 20/10/20 moved the 3C in-window error from {:.1} mV to \
         {:.1} mV — refining the x-grid should help in the regime the x-grid resolves",
        e_coarse * 1e3,
        e_fine * 1e3
    );
}

// ---------------------------------------------------------------------------
// What the solve reports while doing all of the above
// ---------------------------------------------------------------------------

#[test]
fn the_one_c_replay_converges_at_every_step() {
    // A tolerance test can pass while the solver is quietly failing and reporting a
    // plausible number, so the flags are checked separately from the voltages. 1C is
    // comfortably inside the fixed-step scheme's envelope and must be clean throughout;
    // the 3C collapse is allowed its one singular step, which `dfn_cell.rs` pins.
    let rows = parse_csv(CC_1C);
    let mut pack = Pack::new(
        &cfg(dfn(RECOMMENDED_NODES, DEFAULT_SHELLS), rows[0].soc),
        lgm50(),
    )
    .expect("pack builds");
    let env = env_25c();
    let mut unconverged = 0;
    for w in rows.windows(2) {
        let tele = pack.step(w[1].t - w[0].t, Demand::Current(w[1].i), &env);
        if tele.flags.contains(EventFlags::SOLVE_UNCONVERGED) {
            unconverged += 1;
        }
    }
    assert_eq!(
        unconverged, 0,
        "the 1C golden replay raised SOLVE_UNCONVERGED on {unconverged} steps"
    );
}
