//! PyBaMM golden-reference tolerance tests (Phase 1).
//!
//! These replay a committed PyBaMM DFN trajectory through `sim-core` and assert
//! the ECM terminal voltage tracks the DFN reference within a documented,
//! per-scenario tolerance. The reference CSVs live under `tests/golden/` and are
//! (re)generated by `tools/reference/generate.py` (needs PyBaMM; never on the
//! Rust/CI path). Each CSV column is: `time_s, current_a` (discharge-positive),
//! `voltage_v`, `soc`.
//!
//! # What this validates — and what it cannot
//! The chemistry's OCV table and usable capacity are *fitted from the same
//! PyBaMM parameter set* (see `tools/reference/fit_ocv.py` and the LFP TOML
//! provenance), so batsim's coulomb-counted SOC tracks the DFN's stoichiometry
//! SOC exactly under constant current, and the comparison is a genuine test of
//! the electrical model rather than of a capacity or OCV-source mismatch.
//!
//! What remains is the irreducible **ECM-vs-DFN gap**: a 1-RC Thévenin cell has
//! no spatial diffusion, so it cannot reproduce (a) the diverging concentration
//! overpotential at the end of discharge (the voltage "knee", where the DFN
//! collapses to the cut-off with throughput SOC to spare — at 1C this knee
//! arrives as early as soc ≈ 0.2) or (b) the fast kinetic transient at each
//! current step. So each scenario asserts a *tight* tolerance across the mid-SOC
//! window where the models agree; the knee region is excluded by that window and
//! only has to stay inside a generous physical voltage band (the gross-regression
//! guard). R0/RC are still order-of-magnitude placeholders — the main contributor
//! at higher C-rate, hence the wider 1C window tolerance. The pulse scenario adds
//! a targeted check that batsim matches the DFN's *relaxed* voltage at every rest
//! end, which isolates the OCV table and SOC tracking from the kinetic gap.

use sim_core::{ChemistryParams, Demand, Env, Pack, PackConfig, Scatter};

/// One reference sample.
struct Row {
    /// Simulation time \[s\].
    t: f64,
    /// Applied current over the step ending at `t` \[A\], discharge-positive.
    i: f64,
    /// DFN terminal voltage at `t` \[V\].
    v: f64,
    /// Throughput state of charge at `t`, in \[0, 1\].
    soc: f64,
}

/// Parse a golden CSV (skips `#` header lines and the column header).
fn parse_csv(text: &str) -> Vec<Row> {
    text.lines()
        .map(str::trim)
        .filter(|l| !l.is_empty() && !l.starts_with('#') && !l.starts_with("time_s"))
        .map(|l| {
            let mut f = l.split(',');
            let mut next = || f.next().unwrap().parse::<f64>().unwrap();
            Row {
                t: next(),
                i: next(),
                v: next(),
                soc: next(),
            }
        })
        .collect()
}

fn lfp_chem() -> ChemistryParams {
    let text = include_str!("../../../chemistries/lfp_26650_generic.toml");
    sim_data::parse_chemistry(text).expect("LFP chemistry loads")
}

fn env_25c() -> Env {
    Env {
        t_ambient: 298.15,
        t_coolant: None,
    }
}

/// Replay a reference current profile through a 1S1P pack and return batsim's
/// terminal voltage at every row (row 0 mirrors the reference's initial value).
fn replay(chem: ChemistryParams, rows: &[Row]) -> Vec<f64> {
    let cfg = PackConfig {
        series: 1,
        parallel: 1,
        initial_soc: rows[0].soc,
        initial_temp_k: 298.15,
        seed: 0,
        scatter: Scatter::default(),
    };
    let mut pack = Pack::new(&cfg, chem).expect("pack builds");
    let env = env_25c();

    let mut out = Vec::with_capacity(rows.len());
    out.push(rows[0].v); // initial rested state; comparison starts at row 1
    for w in rows.windows(2) {
        let dt = w[1].t - w[0].t;
        let tele = pack.step(dt, Demand::Current(w[1].i), &env);
        out.push(tele.v_terminal);
    }
    out
}

/// Max |batsim − reference| voltage error over rows whose SOC is in `[lo, hi]`.
/// Returns `(max_abs_err, soc_at_max)`.
fn max_err_in_window(rows: &[Row], batsim: &[f64], lo: f64, hi: f64) -> (f64, f64) {
    let mut worst = 0.0_f64;
    let mut at = f64::NAN;
    for (r, &vb) in rows.iter().zip(batsim).skip(1) {
        if r.soc < lo || r.soc > hi {
            continue;
        }
        let e = (vb - r.v).abs();
        if e > worst {
            worst = e;
            at = r.soc;
        }
    }
    (worst, at)
}

/// Max voltage error at *fully relaxed* rest points — rows carrying no current
/// whose next row resumes current (i.e. the end of a rest, where both models
/// have relaxed to OCV). This is the strong OCV-table + SOC-tracking check:
/// it isolates the thermodynamic curve from the ECM-vs-DFN kinetic gap.
fn max_err_at_rest_ends(rows: &[Row], batsim: &[f64]) -> (f64, usize) {
    let mut worst = 0.0_f64;
    let mut count = 0;
    for i in 1..rows.len() - 1 {
        let rested = rows[i].i == 0.0 && rows[i + 1].i > 0.0;
        if rested {
            worst = worst.max((batsim[i] - rows[i].v).abs());
            count += 1;
        }
    }
    (worst, count)
}

/// Every batsim voltage must be finite and inside a generous physical band — the
/// gross-regression guard that replaces a meaninglessly wide full-trajectory
/// tolerance (the ECM-vs-DFN knee gap alone reaches ~1 V at 1C).
fn assert_physical(name: &str, batsim: &[f64]) {
    for (k, &v) in batsim.iter().enumerate() {
        assert!(
            v.is_finite() && (1.5..=3.75).contains(&v),
            "{name}: batsim V={v} at row {k} left the physical band [1.5, 3.75]"
        );
    }
}

/// Load and replay one scenario CSV; return (rows, batsim voltages).
fn load_and_replay(csv: &str, name: &str) -> (Vec<Row>, Vec<f64>) {
    let rows = parse_csv(csv);
    assert!(rows.len() > 2, "{name}: too few rows");
    let batsim = replay(lfp_chem(), &rows);
    (rows, batsim)
}

#[test]
fn lfp_cc_c20_tracks_dfn_in_plateau() {
    // C/20: overpotential is a few mV, so within the plateau the gap is limited
    // by the OCV table's piecewise-linear representation error. The DFN's
    // concentration-collapse knee near soc→0 (hundreds of mV) is outside the
    // window by construction and cannot be reproduced by a 1-RC ECM.
    let csv = include_str!("../../../tests/golden/lfp_26650_generic/cc_c20_25c.csv");
    let (rows, batsim) = load_and_replay(csv, "cc_c20");
    let (win, _) = max_err_in_window(&rows, &batsim, 0.15, 0.95);
    // Measured ~24 mV (mostly OCV-table error at the 0.10-0.20 knee shoulder).
    assert!(
        win < 0.035,
        "cc_c20 plateau error {:.1} mV exceeds 35 mV",
        win * 1e3
    );
    assert_physical("cc_c20", &batsim);
}

#[test]
fn lfp_cc_1c_tracks_dfn_in_plateau() {
    // 1C: the mid-plateau gap is dominated by the placeholder R0/RC vs the true
    // DFN overpotential. The concentration knee arrives early at 1C (~soc 0.2,
    // since the higher current starves the electrode sooner), so the comparison
    // window is confined to the clean mid-SOC band.
    let csv = include_str!("../../../tests/golden/lfp_26650_generic/cc_1c_25c.csv");
    let (rows, batsim) = load_and_replay(csv, "cc_1c");
    let (win, _) = max_err_in_window(&rows, &batsim, 0.45, 0.85);
    // Measured ~70 mV at the low edge, falling to ~30 mV deeper in the plateau.
    assert!(
        win < 0.090,
        "cc_1c plateau error {:.1} mV exceeds 90 mV",
        win * 1e3
    );
    assert_physical("cc_1c", &batsim);
}

#[test]
fn lfp_pulse_relax_tracks_dfn() {
    // GITT-like C/2 pulses with 20-min rests. Two distinct checks:
    //   * at each fully-relaxed rest end, batsim must match the DFN's relaxed
    //     voltage tightly — the direct OCV-table + SOC-tracking validation;
    //   * during pulses the ECM-vs-DFN kinetic transient is larger, bounded by a
    //     looser tolerance (worst ~80 mV at the first, highest-SOC pulse onset).
    let csv = include_str!("../../../tests/golden/lfp_26650_generic/pulse_relax_25c.csv");
    let (rows, batsim) = load_and_replay(csv, "pulse_relax");
    let (rest, n_rest) = max_err_at_rest_ends(&rows, &batsim);
    let (full, _) = max_err_in_window(&rows, &batsim, 0.0, 1.0);
    assert!(
        n_rest >= 5,
        "expected several rest ends, found {n_rest} (CSV format changed?)"
    );
    assert!(
        rest < 0.020,
        "pulse rest-end OCV error {:.1} mV exceeds 20 mV",
        rest * 1e3
    );
    assert!(
        full < 0.100,
        "pulse transient error {:.1} mV exceeds 100 mV",
        full * 1e3
    );
    assert_physical("pulse_relax", &batsim);
}
