//! PyBaMM SPM golden-reference tolerance tests (Phase 6, slice E).
//!
//! These replay a committed PyBaMM **SPM** trajectory through `sim-core`'s own SPM
//! and assert the terminal voltage tracks it within a documented, per-scenario
//! tolerance. The reference CSVs live under `tests/golden/nmc_21700_lgm50/` and are
//! (re)generated by `tools/reference/generate.py` (needs PyBaMM; never on the
//! Rust/CI path). Columns: `time_s, current_a` (discharge-positive), `voltage_v`,
//! `soc`.
//!
//! # Why this is a far tighter test than `pybamm_golden.rs`, and what is left over
//! The Phase 1 goldens compare an **ECM against a DFN** — two different models — so
//! their tolerances are dominated by an irreducible modelling gap and have to be
//! confined to SOC windows where the two can agree at all. Here both sides are the
//! *same model form* (Fickian solid diffusion in one spherical particle per
//! electrode, symmetric Butler–Volmer kinetics, uniform electrolyte) evaluated on
//! the *same parameter set*, so a disagreement is an implementation or
//! discretisation difference and nothing else. Checked rather than assumed:
//! PyBaMM's SPM reports `X-averaged electrolyte overpotential [V]` as **exactly
//! zero** throughout, so it carries no electrolyte term batsim's model omits.
//!
//! What remains is three things, and they are what the tolerances below are made of:
//!
//! * **The OCP tables.** batsim interpolates two committed tables; PyBaMM evaluates
//!   Chen2020's fitted functions. The tables' own documented interpolation error is
//!   1.90 mV (graphite) and 1.88 mV (NMC), so ~2–3 mV is a **floor** no shell count
//!   can get under. Every measured worst case below is within a small multiple of it.
//! * **The radial grid.** batsim runs `N` finite volumes; the reference runs 200 and
//!   is converged (see `common.Reference`). This is the one knob, and
//!   [`shell_count_convergence_puts_the_documented_default_at_the_floor`] measures it.
//! * **The timestep.** batsim takes one backward-Euler step per CSV row (5–30 s);
//!   the reference is adaptive. First-order-in-time error shows up as the largest
//!   single-row disagreements, and they sit at the *first* step of a CC scenario,
//!   where the surface gradient is establishing fastest.
//!
//! # What these tests cannot see
//! Every assertion here is a **tolerance**, and slice C2 lost two rounds to changes
//! no tolerance could see (a one-ULP `FARADAY_C_PER_MOL`, and a `(c·vol)/vol` round
//! trip). The exact-bit defences for the SPM path are `spm_exact_bits.rs` in this
//! same directory, plus the out-of-tree trajectory instrument described in
//! `docs/plans/phase-6-porous-electrodes.md`. A tolerance that rejects a dropped
//! overpotential term but not a changed constant leaves that hole open, and it is
//! named here so the two files are read together.

use sim_core::spm::DEFAULT_SHELLS;
use sim_core::{
    CellModelConfig, ChemistryParams, Demand, Env, Pack, PackConfig, Scatter, ThermalConfig,
};

/// One reference sample.
struct Row {
    /// Simulation time \[s\].
    t: f64,
    /// Applied current over the step ending at `t` \[A\], discharge-positive.
    i: f64,
    /// Reference terminal voltage at `t` \[V\].
    v: f64,
    /// Throughput state of charge at `t`, in \[0, 1\].
    soc: f64,
}

/// Parse a golden CSV (skips `#` header lines and the column header).
fn parse_csv(text: &str) -> Vec<Row> {
    text.lines()
        .map(str::trim)
        .filter(|l| !l.is_empty() && !l.starts_with('#') && !l.starts_with("time_s"))
        .map(|l| {
            let mut f = l.split(',');
            let mut next = || f.next().unwrap().parse::<f64>().unwrap();
            Row {
                t: next(),
                i: next(),
                v: next(),
                soc: next(),
            }
        })
        .collect()
}

const CC_C5: &str = include_str!("../../../tests/golden/nmc_21700_lgm50/spm_cc_c5_25c.csv");
const CC_1C: &str = include_str!("../../../tests/golden/nmc_21700_lgm50/spm_cc_1c_25c.csv");
const PULSE: &str = include_str!("../../../tests/golden/nmc_21700_lgm50/spm_pulse_relax_25c.csv");
const DFN_1C: &str = include_str!("../../../tests/golden/nmc_21700_lgm50/dfn_cc_1c_25c.csv");

fn lgm50() -> ChemistryParams {
    let text = include_str!("../../../chemistries/nmc_21700_lgm50.toml");
    sim_data::parse_chemistry(text).expect("LG M50 chemistry loads")
}

fn env_25c() -> Env {
    Env {
        t_ambient: 298.15,
        t_coolant: None,
    }
}

/// Replay a reference current profile through a 1S1P SPM pack. Returns batsim's
/// terminal voltage and its SOC *readout* at every row (row 0 mirrors the
/// reference's initial values, so the comparison starts at row 1).
///
/// The pack is isothermal and has no BMS: the reference is isothermal too, and a
/// protection layer clamping a demand would make this a test of the clamp.
fn replay(rows: &[Row], shells: usize) -> (Vec<f64>, Vec<f64>) {
    let cfg = PackConfig {
        aging: None,
        bms: None,
        thermal: ThermalConfig::Isothermal,
        series: 1,
        parallel: 1,
        initial_soc: rows[0].soc,
        initial_temp_k: 298.15,
        seed: 0,
        scatter: Scatter::default(),
        cell_model: CellModelConfig::Spm { shells },
    };
    let mut pack = Pack::new(&cfg, lgm50()).expect("an SPM pack on this chemistry builds");
    let env = env_25c();

    let mut v = Vec::with_capacity(rows.len());
    let mut soc = Vec::with_capacity(rows.len());
    v.push(rows[0].v);
    soc.push(rows[0].soc);
    for w in rows.windows(2) {
        let tele = pack.step(w[1].t - w[0].t, Demand::Current(w[1].i), &env);
        v.push(tele.v_terminal);
        soc.push(tele.soc_true);
    }
    (v, soc)
}

/// Worst `|batsim − reference|` terminal voltage over the whole trajectory, and the
/// SOC it occurred at.
///
/// Deliberately **not** windowed by SOC, which every Phase 1 golden has to be. An
/// SPM reproduces the end-of-discharge concentration collapse that an ECM cannot,
/// so there is no region of the trajectory this comparison has to look away from —
/// and saying so with a full-range assertion is a stronger claim than any window.
fn worst_v_error(rows: &[Row], batsim: &[f64]) -> (f64, f64) {
    let mut worst = 0.0_f64;
    let mut at = f64::NAN;
    for (r, &vb) in rows.iter().zip(batsim).skip(1) {
        let e = (vb - r.v).abs();
        if e > worst {
            worst = e;
            at = r.soc;
        }
    }
    (worst, at)
}

/// Worst voltage error at *fully relaxed* rest ends — rows carrying no current
/// whose next row resumes current. Both models have equilibrated there, so this
/// isolates the OCP tables and the lithium inventory from every transient term.
fn worst_at_rest_ends(rows: &[Row], batsim: &[f64]) -> (f64, usize) {
    let mut worst = 0.0_f64;
    let mut count = 0;
    for i in 1..rows.len() - 1 {
        if rows[i].i == 0.0 && rows[i + 1].i > 0.0 {
            worst = worst.max((batsim[i] - rows[i].v).abs());
            count += 1;
        }
    }
    (worst, count)
}

/// Every batsim voltage must be finite and inside this cell's own window plus a
/// margin — the gross-regression guard.
fn assert_physical(name: &str, batsim: &[f64]) {
    for (k, &v) in batsim.iter().enumerate() {
        assert!(
            v.is_finite() && (2.0..=4.5).contains(&v),
            "{name}: batsim V={v} at row {k} left the physical band [2.0, 4.5]"
        );
    }
}

fn load(csv: &str, name: &str, shells: usize) -> (Vec<Row>, Vec<f64>, Vec<f64>) {
    let rows = parse_csv(csv);
    assert!(
        rows.len() > 100,
        "{name}: too few rows — CSV format changed?"
    );
    let (v, soc) = replay(&rows, shells);
    (rows, v, soc)
}

// ---------------------------------------------------------------------------
// The three batsim-vs-PyBaMM scenarios
// ---------------------------------------------------------------------------

#[test]
fn spm_cc_c5_tracks_pybamm_spm() {
    // C/5 from full to the 2.5 V cut-off, sampled every 30 s. The gentlest rate, and
    // therefore the one whose disagreement is almost entirely the OCP tables: at
    // 1.03 A the radial gradient is a few tenths of a percent of stoichiometry.
    // The whole trajectory is compared, cut-off knee included.
    let (rows, v, _) = load(CC_C5, "cc_c5", DEFAULT_SHELLS);
    let (worst, at) = worst_v_error(&rows, &v);
    // Measured 2.6 mV, worst at the first step. The floor is the OCP tables' own
    // 1.90 + 1.88 mV interpolation error; 5 mV is that floor with room for the
    // 30 s backward-Euler step and nothing else.
    assert!(
        worst < 0.005,
        "cc_c5 worst error {:.2} mV (at soc {at:.3}) exceeds 5 mV",
        worst * 1e3
    );
    assert_physical("cc_c5", &v);
}

#[test]
fn spm_cc_1c_tracks_pybamm_spm() {
    // 1C from full, sampled every 5 s. Five times the flux of the C/5 case, so the
    // radial gradient is genuinely large and this is the scenario the shell count
    // is answerable to.
    let (rows, v, _) = load(CC_1C, "cc_1c", DEFAULT_SHELLS);
    let (worst, at) = worst_v_error(&rows, &v);
    // Measured 6.7 mV, at the *first* step (soc ≈ 0.999) where the surface gradient
    // establishes inside one 5 s step. Everything after row 1 sits under 4 mV.
    assert!(
        worst < 0.012,
        "cc_1c worst error {:.2} mV (at soc {at:.3}) exceeds 12 mV",
        worst * 1e3
    );
    assert_physical("cc_1c", &v);
}

#[test]
fn spm_pulse_relax_tracks_pybamm_spm() {
    // GITT-like C/2 pulses with 20-minute rests. Two checks, because the rests make
    // a sharper one available: the relaxed points test the OCP tables and the
    // inventory with every transient term equilibrated away, while the pulses test
    // the transient itself.
    let (rows, v, _) = load(PULSE, "pulse_relax", DEFAULT_SHELLS);
    let (rest, n_rest) = worst_at_rest_ends(&rows, &v);
    let (worst, at) = worst_v_error(&rows, &v);
    assert!(
        n_rest >= 5,
        "expected several rest ends, found {n_rest} (CSV format changed?)"
    );
    // Measured: 0.3 mV relaxed, 1.9 mV worst including the pulse transients. The
    // relaxed figure is *below* the OCP tables' stated interpolation error, which is
    // the expected outcome — that error is a worst case over the table's whole
    // range, not the error at these particular stoichiometries.
    assert!(
        rest < 0.002,
        "pulse rest-end error {:.2} mV exceeds 2 mV",
        rest * 1e3
    );
    assert!(
        worst < 0.005,
        "pulse worst error {:.2} mV (at soc {at:.3}) exceeds 5 mV",
        worst * 1e3
    );
    assert_physical("pulse_relax", &v);
}

// ---------------------------------------------------------------------------
// The SOC readout, which is a different claim from the voltage
// ---------------------------------------------------------------------------

#[test]
fn the_spm_soc_readout_tracks_the_references_coulomb_count() {
    // `Telemetry::soc_true` is coulomb-counted for an ECM and *derived from mean
    // stoichiometry* for an SPM — a readout of the lithium inventory rather than a
    // counter. So the two agreeing is a real check on the finite-volume scheme's
    // conservation and on `kappa` (the charge-to-stoichiometry scale), not the
    // arithmetic identity it is on the ECM path.
    //
    // Run on the 1C scenario, where the radial profile is most developed and a
    // scheme that leaked lithium into the interior would show it.
    let (rows, _, soc) = load(CC_1C, "cc_1c", DEFAULT_SHELLS);
    let mut worst = 0.0_f64;
    for (r, &sb) in rows.iter().zip(&soc).skip(1) {
        worst = worst.max((sb - r.soc).abs());
    }
    // Measured 4.4e-7, and it is not noise: it is the reference's own capacity
    // rounding. The CSV counts against 5.153198 A.h (six decimals, as printed) while
    // the chemistry's geometry holds 5.153198326 A.h, a 6.3e-8 relative difference
    // that accumulates across a full discharge. Nothing here is free to drift by
    // more than that.
    assert!(
        worst < 5e-6,
        "SPM soc readout drifts from the reference coulomb count by {worst:.2e}"
    );
}

// ---------------------------------------------------------------------------
// The shell count, decided by this curve rather than by taste
// ---------------------------------------------------------------------------

#[test]
fn shell_count_convergence_puts_the_documented_default_at_the_floor() {
    // The open question slice C2 left for slice E: what is `N`? The answer is a
    // measurement, and this is it — worst-case voltage error against the converged
    // reference at four shell counts on the rate that stresses the grid hardest.
    //
    // Two assertions, and the second is the one that makes this a test rather than
    // a printout: a coarse grid must be **materially worse**. Without it the whole
    // thing passes just as well if the shell count stops doing anything.
    let rows = parse_csv(CC_1C);
    let err = |n: usize| {
        let (v, _) = replay(&rows, n);
        worst_v_error(&rows, &v).0
    };

    let coarse = err(5);
    let default = err(DEFAULT_SHELLS);
    let fine = err(40);

    // Measured: N=5 → 53.1 mV, N=10 → 24.1 mV, N=20 → 6.7 mV, N=40 → 5.0 mV.
    assert!(
        default < 0.012,
        "N={DEFAULT_SHELLS} worst error {:.1} mV is no longer at the floor",
        default * 1e3
    );
    assert!(
        coarse > 4.0 * default,
        "N=5 ({:.1} mV) is not materially worse than N={DEFAULT_SHELLS} ({:.1} mV) — \
         the shell count has stopped mattering, and this test would pass with the \
         radial solve removed",
        coarse * 1e3,
        default * 1e3
    );
    // And refining past the default buys nothing, because the residual is the OCP
    // tables rather than the grid. Stated as a bound rather than an equality: the
    // claim is "no longer improving", not "identical".
    assert!(
        fine > 0.5 * default,
        "N=40 ({:.1} mV) improved on N={DEFAULT_SHELLS} ({:.1} mV) by more than 2x — \
         the default is under-resolved and DEFAULT_SHELLS should move",
        fine * 1e3,
        default * 1e3
    );
}

// ---------------------------------------------------------------------------
// The SPM-vs-DFN gap: a physics result, not an assertion about batsim
// ---------------------------------------------------------------------------

#[test]
fn the_spm_and_dfn_references_disagree_by_the_physics_spm_leaves_out() {
    // `dfn_cc_1c_25c.csv` is the *same* scenario and parameter set as
    // `spm_cc_1c_25c.csv`, run as a DFN. Nothing in this file asserts batsim against
    // it; it is committed so the gap between a single-particle model and a full
    // porous-electrode one is visible on the same axes, which is the pedagogy the
    // `Spm` variant exists for.
    //
    // The assertion is a guard on the CSVs rather than on the engine: if someone
    // regenerates the DFN golden with the SPM model (a one-word edit in
    // `generate.py`'s scenario table), the two files become the same trajectory and
    // the teaching example silently evaporates. A gap that must be *present* is the
    // only thing that notices.
    let spm = parse_csv(CC_1C);
    let dfn = parse_csv(DFN_1C);
    let mut worst = 0.0_f64;
    let mut matched = 0;
    for d in &dfn {
        if let Some(s) = spm.iter().find(|x| (x.t - d.t).abs() < 1e-9) {
            matched += 1;
            worst = worst.max((s.v - d.v).abs());
        }
    }
    assert!(
        matched > 100,
        "the two references share too few sample times"
    );
    // Measured 71 mV at 1C: the DFN's electrolyte transport and its distribution of
    // reaction current across the electrode thickness, neither of which a single
    // particle has.
    assert!(
        worst > 0.020,
        "SPM and DFN references differ by only {:.1} mV — is dfn_cc_1c_25c.csv \
         actually a DFN run?",
        worst * 1e3
    );
}
