"""Generate batsim's committed golden-reference CSVs from PyBaMM DFN runs.

    python tools/reference/generate.py            # all chemistries + scenarios
    python tools/reference/generate.py lfp_26650_generic

Writes one CSV per (chemistry, scenario) under `tests/golden/<chem_id>/`. Each
CSV carries a comment header recording the PyBaMM version, parameter set, and
scenario so a committed golden is reproducible against a known reference. The
Rust integration tests (crates/sim-data/tests/pybamm_golden.rs) replay the
`current_a` column through `sim-core` and compare `voltage_v` within a
per-scenario, documented tolerance.

Columns: time_s, current_a (discharge-positive), voltage_v, soc.

Not shipped; requires PyBaMM (see requirements.txt). Never on the Rust/CI path.
"""

from __future__ import annotations

import sys
from pathlib import Path

import numpy as np

from common import PARAM_SETS, T_REF_K, fit_chemistry, run_cc_discharge, run_pulse_relax

# Repo root = two levels up from this file (tools/reference/generate.py).
GOLDEN_DIR = Path(__file__).resolve().parents[2] / "tests" / "golden"

# (filename, human description, generator, kwargs). The generator returns
# (time_s, current_a, voltage_v, soc).
SCENARIOS = [
    (
        "cc_c20_25c.csv",
        "C/20 constant-current discharge from full, isothermal 25 degC",
        run_cc_discharge,
        {"c_rate": 1.0 / 20.0, "dt_s": 30.0},
    ),
    (
        "cc_1c_25c.csv",
        "1C constant-current discharge from full, isothermal 25 degC",
        run_cc_discharge,
        {"c_rate": 1.0, "dt_s": 5.0},
    ),
    (
        "pulse_relax_25c.csv",
        "GITT-like C/2 discharge pulses with 20-min rests, isothermal 25 degC",
        run_pulse_relax,
        {"c_rate": 0.5, "dt_s": 10.0},
    ),
]


def write_csv(path: Path, header_lines: list[str], t, i, v, soc) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="\n", encoding="utf-8") as f:
        for line in header_lines:
            f.write(f"# {line}\n")
        f.write("time_s,current_a,voltage_v,soc\n")
        for ti, ii, vi, si in zip(t, i, v, soc):
            f.write(f"{ti:.6f},{ii:.6f},{vi:.6f},{si:.6f}\n")


def generate_for(chem_id: str) -> None:
    fit = fit_chemistry(chem_id)
    print(f"{chem_id}: {fit.param_set} (pybamm {fit.pybamm_version}), "
          f"Q_use={fit.capacity_ah:.6f} A.h, "
          f"OCV table lin-err={fit.max_lin_err_v * 1e3:.2f} mV")
    for fname, desc, gen, kwargs in SCENARIOS:
        t, i, v, soc = gen(chem_id, fit, **kwargs)
        header = [
            f"batsim golden reference - {chem_id} - {fname}",
            f"scenario: {desc}",
            f"source: PyBaMM {fit.param_set} DFN (isothermal {T_REF_K:.2f} K), "
            f"pybamm {fit.pybamm_version}",
            f"capacity_ah (usable, stoichiometry window) = {fit.capacity_ah:.6f}",
            "sign: positive current = discharge (batsim convention)",
            "generated by tools/reference/generate.py - do not edit by hand",
        ]
        out = GOLDEN_DIR / chem_id / fname
        write_csv(out, header, t, i, v, soc)
        print(f"  wrote {out.relative_to(GOLDEN_DIR.parent.parent)} "
              f"({len(t)} rows, V {np.min(v):.3f}..{np.max(v):.3f})")


def main(argv: list[str]) -> int:
    if len(argv) == 1:
        targets = list(PARAM_SETS)
    else:
        targets = argv[1:]
        for t in targets:
            if t not in PARAM_SETS:
                print(f"unknown chemistry: {t}", file=sys.stderr)
                return 2
    for chem_id in targets:
        generate_for(chem_id)
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
